const enemies = {
	enemies: {
		Alistar: {
			name: "Alistar",
			type: "tank",
			classe: "Warrior",
			stats: {
				speed: 1,
				detectionRange: 5,
				hitDistance: 1,
				autoAttackDamage: 1,
				autoAttackCd: 1,
				strength: 23,
				intelligence: 5,
				dexterity: 18,
				hp: 450,
				mana: 20,
				physiqueArmor: 35,
				magicArmor: 15,
			},
			scale: 1,
			radius: 0.5,
			xp: 75,
			lv: 4,
			inventory: [],
			png: "Alistar.jpg",
			glb: "Alistar.fbx",
			animations: {
				walk_path: "models/enemies/animations/Alistar_Walk.fbx",
				autoattack_path: "models/enemies/animations/Alistar_AutoAttack.fbx",
				dying_path: "models/enemies/animations/Alistar_Dying.fbx",
				skill1_path: "models/enemies/animations/Alistar_Skill1.fbx",
				skill2_path: "models/enemies/animations/Alistar_Skill2.fbx",
				skill3_path: "models/enemies/animations/Alistar_Skill3.fbx",
				ultimat_path: "models/enemies/animations/Alistar_Ultimat.fbx",
			},
		},
		Torp: {
			id: "enemy_torp_base",
			type: "Torp",
			name: "Torp",
			classe: "Warrior",
			stats: {
				speed: 1,
				detectionRange: 5,
				hitDistance: 2.5,
				autoAttackDamage: 15,
				autoAttackCd: 1,
				strength: 23,
				intelligence: 5,
				dexterity: 18,
				hp: 150,
				mana: 20,
				physiqueArmor: 20,
				magicArmor: 10,
				attackSpeed: 1000, // ms
			},
			scale: 1.5,
			radius: 0.6,
			xp: 35,
			lv: 4,
			inventory: [],
			png: "Torp.jpg",
			glb: "Torp.fbx", // dans enemies/
			animations: {
				walk_path: "models/enemies/animations/Torp_Walk.fbx",
				autoattack_path: "models/enemies/animations/Torp_AutoAttack.fbx",
				dying_path: "models/enemies/animations/Torp_Dying.fbx",
				skill1_path: "models/enemies/animations/Torp_Skill1.fbx",
				skill2_path: "models/enemies/animations/Torp_Skill2.fbx",
				skill3_path: "models/enemies/animations/Torp_Skill3.fbx",
				ultimat_path: "models/enemies/animations/Torp_Ultimat.fbx",
			},
		},
		Zephyr: {
			id: "enemy_zephyr_base",
			type: "Zephyr",
			name: "Zephyr",
			classe: "Warrior",
			stats: {
				speed: 1,
				detectionRange: 5,
				hitDistance: 4.0, // Ranged
				autoAttackDamage: 25,
				autoAttackCd: 1,
				strength: 23,
				intelligence: 5,
				dexterity: 18,
				hp: 80,
				mana: 20,
				physiqueArmor: 5,
				magicArmor: 5,
				attackSpeed: 1200, // ms
			},
			scale: 0.8,
			radius: 0.4,
			xp: 25,
			lv: 4,
			inventory: [],
			png: "Zephyr.jpg",
			glb: "Zephyr.fbx", // dans enemies/
			animations: {
				walk_path: "models/enemies/animations/Zephyr_Walk.fbx",
				autoattack_path: "models/enemies/animations/Zephyr_AutoAttack.fbx",
				dying_path: "models/enemies/animations/Zephyr_Dying.fbx",
				skill1_path: "models/enemies/animations/Zephyr_Skill1.fbx",
				skill2_path: "models/enemies/animations/Zephyr_Skill2.fbx",
				skill3_path: "models/enemies/animations/Zephyr_Skill3.fbx",
				ultimat_path: "models/enemies/animations/Zephyr_Ultimat.fbx",
			},
		},
	},
};

module.exports = enemies;
